version: "3.8"  # optional since v1.27.0
services:

  crawler:
    ports:
      - "9229:9229"
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - ./node_modules/:/app/node_modules
    command: npm run debug
